version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-chat
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  celery-worker:
    env_file:
      - ./backend/.env
    build: ./backend
    container_name: celery-worker
    command: celery -A app.core.celery worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/0
      - FLASK_CONFIG=development
      - DEV_DATABASE_URL=postgresql://postgres:1234@host.docker.internal:5432/visamadeeasy_dev

  celery-beat:
    env_file:
      - ./backend/.env
    build: ./backend
    container_name: celery-beat
    command: celery -A app.core.celery beat --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/0
      - FLASK_CONFIG=development

volumes:
  redis_data: