"""add pinned fields to conversation

Revision ID: 8b0a9c021adc
Revises: c7e113cd569c
Create Date: 2025-09-24 21:54:31.098818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b0a9c021adc'
down_revision = 'c7e113cd569c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pinned', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('pinned_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_column('pinned_at')
        batch_op.drop_column('pinned')

    # ### end Alembic commands ###
