"""smart endpoint phases 1-4

Revision ID: c4531c3330c6
Revises: 3bc18fffc1a3
Create Date: 2025-09-22 17:08:32.682823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4531c3330c6'
down_revision = '3bc18fffc1a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_file', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uploaded_file_user_id_fkey'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('uploaded_file_user_id_fkey'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
