"""add file_size and mime_type to uploaded_file

Revision ID: ef5ad31c38f3
Revises: b52fcca9e54b
Create Date: 2025-09-19 21:04:34.434081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef5ad31c38f3'
down_revision = 'b52fcca9e54b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_size', sa.BigInteger(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('mime_type', sa.String(length=100), nullable=True))

    # remove server default after backfilling existing rows
    with op.batch_alter_table('uploaded_file', schema=None) as batch_op:
        batch_op.alter_column('file_size', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_file', schema=None) as batch_op:
        batch_op.drop_column('mime_type')
        batch_op.drop_column('file_size')
    # ### end Alembic commands ###
